"""Explicit, on-demand benchmark/inspection exports.

Importing one supported inspector must not eagerly load every historical PP/MoE
experiment. The original named export targets are preserved during curation;
research-only aliases will be removed with their verified consumers. No model
function bodies or numerical source registrations are changed here.
"""

from importlib import import_module as _import_module

_EXPORTS = {
    "ACCEPTED_DECODE_PROJECTION_HLO_GZIP_SHA256": "association_fingerprint",
    "ACCEPTED_DECODE_PROJECTION_HLO_RAW_SHA256": "association_fingerprint",
    "ACCEPTED_DECODE_PROJECTION_MANIFEST_SHA256": "association_fingerprint",
    "ACCEPTED_DENSE_PARTIALS_KEYS": "association_fingerprint",
    "ACCEPTED_DENSE_PARTIALS_NPZ_SHA256": "association_fingerprint",
    "ACCEPTED_DENSE_PARTIALS_RAW_SHA256": "association_fingerprint",
    "ACCEPTED_DENSE_PARTIALS_SHAPE": "association_fingerprint",
    "ACCEPTED_M2048_HLO_GZIP_SHA256": "m2048_association_fingerprint",
    "ACCEPTED_M2048_HLO_RAW_SHA256": "m2048_association_fingerprint",
    "ACCEPTED_M2048_SOURCE_TAG": "m2048_association_fingerprint",
    "ACCEPTED_SOURCE_VALIDITY": "integrated_dense_rms",
    "ACCEPTED_TP32_MODEL_AXIS_RECIPE": "association_fingerprint",
    "CHECKPOINT_SUCCESS_SHA256": "integrated_dense_rms",
    "CollectiveChainConfig": "collective_chain",
    "CollectiveKind": "collective_chain",
    "CompiledFeature2Boundary": "pp16_feature_sharded_state",
    "CompiledIntegratedDenseRms": "integrated_dense_rms",
    "CompiledM2048StrategyNdFingerprint": "m2048_association_fingerprint",
    "CompiledOutputGeometryReplay": "output_geometry",
    "DENSE_RMS_ARRAY_RECORDS": "dense_rms_replay",
    "DENSE_RMS_SOURCE_CODE_HASH": "dense_rms_replay",
    "DENSE_RMS_SOURCE_KEYS": "dense_rms_replay",
    "DENSE_RMS_SOURCE_NPZ_SHA256": "dense_rms_replay",
    "DENSE_RMS_SOURCE_REMOTE_OBJECTS_SHA256": "dense_rms_replay",
    "DENSE_RMS_SOURCE_RUNNER_SHA256": "dense_rms_replay",
    "DENSE_RMS_SOURCE_SUCCESS_SHA256": "dense_rms_replay",
    "DENSE_RMS_SOURCE_SUMMARY_SHA256": "dense_rms_replay",
    "DENSE_RMS_SOURCE_TAG": "dense_rms_replay",
    "DenseRmsInputs": "dense_rms_replay",
    "Feature2PrefillChunk": "pp16_feature2_prefill",
    "Feature2PrefillGraph": "pp16_feature2_prefill",
    "Feature2PrefillInputs": "pp16_feature2_prefill",
    "Feature2PrefillNode": "pp16_feature2_prefill",
    "Feature2PrefillSource": "pp16_feature2_prefill",
    "Feature2PrefillTensor": "pp16_feature2_prefill",
    "Feature2SplitRecord": "pp16_feature_sharded_state",
    "Feature2TensorRead": "pp16_feature_sharded_state",
    "Feature2WeightRole": "pp16_feature2_prefill",
    "GateCDenseResult": "gate_c",
    "GateCDsaResult": "gate_c",
    "GateCIndexShareResult": "gate_c",
    "INTEGRATED_DENSE_ACCEPTED_SOURCE_STABLEHLO_SHA256": "integrated_dense_rms_hlo",
    "INTEGRATED_DENSE_NATIVE_SOURCE_OPTIMIZED_HLO_SHA256": "integrated_dense_rms_hlo",
    "INTEGRATED_DENSE_NATIVE_SOURCE_STABLEHLO_SHA256": "integrated_dense_rms_hlo",
    "INTEGRATED_DENSE_ORDINAL_RMS_STABLEHLO_SHA256": "integrated_dense_rms_hlo",
    "INTEGRATED_DENSE_PREDENSE_SPLIT_RMS_STABLEHLO_SHA256": "integrated_dense_rms_hlo",
    "INTEGRATED_DENSE_RMS_STABLEHLO_SHA256": "integrated_dense_rms_hlo",
    "INTEGRATED_DENSE_SPLIT_RMS_STABLEHLO_SHA256": "integrated_dense_rms_hlo",
    "IntegratedDenseRmsInputs": "integrated_dense_rms",
    "IntegratedDenseWeights": "integrated_dense_rms",
    "LatencyDistribution": "collective_chain",
    "LoadedFeature2SelectiveCheckpoint": "pp16_feature2_loader",
    "LoweredFeature2Transport": "pp16_feature_sharded_state",
    "M1_AUTO_BF16_LAYOUT": "output_geometry",
    "M1_PALLAS_M8_SCRATCH_SHAPE": "output_geometry",
    "M2048StrategyNdFingerprintConfig": "m2048_association_fingerprint",
    "M2048_ROWS": "m2048_association_fingerprint",
    "M2048_SEED": "m2048_association_fingerprint",
    "M2048_TRIALS": "m2048_association_fingerprint",
    "M2048_WIDTH": "m2048_association_fingerprint",
    "M32_BF16_LAYOUT": "output_geometry",
    "NATIVE_SOURCE_ATTENDED_LATENT_KEY": "integrated_dense_rms",
    "NATIVE_SOURCE_ATTENDED_LATENT_SHA256": "integrated_dense_rms",
    "NATIVE_SOURCE_NPZ_SHA256": "integrated_dense_rms",
    "NATIVE_SOURCE_REMOTE_OBJECTS_SHA256": "integrated_dense_rms",
    "NATIVE_SOURCE_RUNNER_SHA256": "integrated_dense_rms",
    "NATIVE_SOURCE_SUCCESS_SHA256": "integrated_dense_rms",
    "NATIVE_SOURCE_SUMMARY_SHA256": "integrated_dense_rms",
    "NATIVE_SOURCE_TAG": "integrated_dense_rms",
    "NATIVE_SOURCE_TOKEN_IDS": "integrated_dense_rms",
    "NativeSourceInputs": "integrated_dense_rms",
    "NativeSourceWeights": "integrated_dense_rms",
    "OUTPUT_GEOMETRY_DENSE_ROW_RAW_SHA256": "output_geometry",
    "OUTPUT_GEOMETRY_INVERSE_RAW_SHA256": "output_geometry",
    "OUTPUT_GEOMETRY_OPTIMIZED_HLO_SHA256": "output_geometry",
    "OUTPUT_GEOMETRY_STABLEHLO_SHA256": "output_geometry",
    "OutputGeometryInputs": "output_geometry",
    "POST_ATTENTION_NORM_RAW_SHA256": "integrated_dense_rms",
    "PP16_FEATURE2_ACCEPTED_CARRIED_HALF_SHA256": "pp16_feature_sharded_state",
    "PP16_FEATURE2_ACCEPTED_CARRIED_SHA256": "pp16_feature_sharded_state",
    "PP16_FEATURE2_ACCEPTED_DENSE_HALF_SHA256": "pp16_feature_sharded_state",
    "PP16_FEATURE2_ACCEPTED_DENSE_SHA256": "pp16_feature_sharded_state",
    "PP16_FEATURE2_ACCEPTED_INPUT_RESIDUAL_HALF_SHA256": "pp16_feature_sharded_state",
    "PP16_FEATURE2_ACCEPTED_INPUT_RESIDUAL_SHA256": "pp16_feature_sharded_state",
    "PP16_FEATURE2_CONTEXT_LENGTH": "pp16_feature_sharded_state",
    "PP16_FEATURE2_CURRENT_POSITION": "pp16_feature2_prefill",
    "PP16_FEATURE2_CURRENT_TOKEN_ID": "pp16_feature2_prefill",
    "PP16_FEATURE2_DSA_TOP_K": "pp16_feature2_prefill",
    "PP16_FEATURE2_LOCAL_GROUP": "pp16_feature2_prefill",
    "PP16_FEATURE2_LOCAL_ROWS_PER_PAGE": "pp16_feature2_prefill",
    "PP16_FEATURE2_LOGICAL_PAGES": "pp16_feature2_prefill",
    "PP16_FEATURE2_LOGICAL_PAGE_SIZE": "pp16_feature2_prefill",
    "PP16_FEATURE2_MINIMUM_STATE_BYTES_PER_DEVICE": "pp16_feature_sharded_state",
    "PP16_FEATURE2_N82_SCALE_SHA256": "pp16_feature_sharded_state",
    "PP16_FEATURE2_N82_WEIGHT_SHA256": "pp16_feature_sharded_state",
    "PP16_FEATURE2_PREFILL_CHUNK": "pp16_feature2_prefill",
    "PP16_FEATURE2_PREFILL_VALID_ROWS": "pp16_feature2_prefill",
    "PP16_FEATURE2_RUNTIME_MANIFEST_SHA256": "pp16_feature_sharded_state",
    "PP16_FEATURE2_SELECTED_READS_SHA256": "pp16_feature2_prefill",
    "PP16_FEATURE2_SELECTED_WEIGHT_BYTES_PER_DEVICE": "pp16_feature_sharded_state",
    "PP16_FEATURE2_TIE_POLICY": "pp16_feature2_prefill",
    "PairedTransportConfig": "paired_transport",
    "PairedTransportKind": "paired_transport",
    "REAL_LAYER_OUTPUT_TOLERANCE": "one_layer",
    "ROUTE_WEIGHT_TOLERANCE": "one_layer",
    "STRATEGY_ND_ALGORITHM": "association_fingerprint",
    "StrategyNdFingerprintConfig": "association_fingerprint",
    "TensorTolerance": "one_layer",
    "TransportChainConfig": "transport_chain",
    "TransportKind": "transport_chain",
    "WS32_ONE_LAYER_INPUT_SPECS": "ws32_one_layer",
    "WS32_ONE_LAYER_OUTPUT_SPEC": "ws32_one_layer",
    "WS32_PALLAS_REAL_LAYER_LIVE_CLOSURE_SHA256": "ws32_pallas_one_layer",
    "WS32_PALLAS_REAL_LAYER_OPTIMIZED_HLO_SHA256": "ws32_pallas_one_layer",
    "WS32_PALLAS_REAL_LAYER_STABLEHLO_SHA256": "ws32_pallas_one_layer",
    "Ws32DecoderHloReport": "ws32_decoder",
    "Ws32ExactDsaMaterializerHloReport": "ws32_decoder",
    "Ws32OneLayerHloReport": "ws32_one_layer",
    "Ws32PallasOneLayerHloReport": "ws32_pallas_one_layer",
    "accepted_tp32_model_axis_device_ids": "association_fingerprint",
    "addressable_checksum": "collective_chain",
    "analyze_m2048_row0_association": "m2048_association_fingerprint",
    "analyze_m32_strategy_nd_fingerprint": "association_fingerprint",
    "analyze_strategy_nd_fingerprint": "association_fingerprint",
    "array_sha256": "association_fingerprint",
    "assemble_native_source_weights": "integrated_dense_rms",
    "benchmark_collective_chain": "collective_chain",
    "benchmark_paired_transport": "paired_transport",
    "benchmark_transport_chain": "transport_chain",
    "build_collective_chain": "collective_chain",
    "build_feature2_boundary": "pp16_feature_sharded_state",
    "build_feature2_prefill_graph": "pp16_feature2_prefill",
    "build_integrated_dense_rms": "integrated_dense_rms",
    "build_m2048_strategy_nd_fingerprint": "m2048_association_fingerprint",
    "build_output_geometry_replay": "output_geometry",
    "build_paired_transport": "paired_transport",
    "build_strategy_nd_dense_rms_replay": "dense_rms_replay",
    "build_strategy_nd_fingerprint": "association_fingerprint",
    "build_transport_chain": "transport_chain",
    "build_ws32_one_layer_mapped": "ws32_one_layer",
    "build_ws32_pallas_one_layer_mapped": "ws32_pallas_one_layer",
    "collective_chain_hlo_policy": "collective_chain",
    "compare_bounded_tensor": "one_layer",
    "compare_output_geometry_arrays": "output_geometry",
    "derive_feature2_tensor_allowlist": "pp16_feature_sharded_state",
    "execute_integrated_dense_rms": "integrated_dense_rms",
    "execute_m2048_strategy_nd_fingerprint": "m2048_association_fingerprint",
    "execute_native_source_context": "integrated_dense_rms",
    "execute_output_geometry_replay": "output_geometry",
    "execute_strategy_nd_dense_rms_replay": "dense_rms_replay",
    "execute_strategy_nd_fingerprint": "association_fingerprint",
    "feature2_minimum_acquisition_roles": "pp16_feature_sharded_state",
    "generate_m2048_row0_input_bits": "m2048_association_fingerprint",
    "generate_strategy_nd_input_bits": "association_fingerprint",
    "inspect_feature2_selective_plan": "pp16_feature2_loader",
    "integrated_dense_rms_hlo_policy": "integrated_dense_rms_hlo",
    "jax_dtype": "collective_chain",
    "latency_distribution": "collective_chain",
    "load_dense_rms_inputs": "dense_rms_replay",
    "load_feature2_prefill_inputs": "pp16_feature2_prefill",
    "load_feature2_selective_checkpoint": "pp16_feature2_loader",
    "load_integrated_dense_rms_inputs": "integrated_dense_rms",
    "load_output_geometry_inputs": "output_geometry",
    "lower_feature2_transport": "pp16_feature_sharded_state",
    "m2048_source_identity": "m2048_association_fingerprint",
    "m2048_strategy_nd_hlo_policy": "m2048_association_fingerprint",
    "model_axis_to_physical_input_bits": "association_fingerprint",
    "model_axis_weights_to_physical": "integrated_dense_rms",
    "native_source_inputs": "integrated_dense_rms",
    "pack_paired_transport_payload": "paired_transport",
    "pp16_feature2_transport_pairs": "pp16_feature_sharded_state",
    "read_feature2_owner_headers": "pp16_feature_sharded_state",
    "replay_db533_strategy_nd_row0_bits": "association_fingerprint",
    "split_feature2_bf16_bits": "pp16_feature_sharded_state",
    "stage_local_dense_gate_c": "gate_c",
    "stage_local_dsa_fp8_gate_c": "gate_c",
    "stage_local_dsa_gate_c": "gate_c",
    "stage_local_index_share_gate_c": "gate_c",
    "transport_chain_hlo_policy": "transport_chain",
    "unpack_paired_transport_payload": "paired_transport",
    "validate_compiled_transport": "transport_chain",
    "validate_dsa_score_hlo": "dsa",
    "validate_feature2_accepted_state": "pp16_feature_sharded_state",
    "validate_feature2_acquisition_reads": "pp16_feature_sharded_state",
    "validate_feature2_acquisition_scope": "pp16_feature_sharded_state",
    "validate_feature2_boundary_stablehlo": "pp16_feature_sharded_state",
    "validate_feature2_n82_manifest": "pp16_feature_sharded_state",
    "validate_feature2_prefill_graph": "pp16_feature2_prefill",
    "validate_feature2_prefill_inputs": "pp16_feature2_prefill",
    "validate_feature2_transport_contract": "pp16_feature_sharded_state",
    "validate_feature2_transport_stablehlo": "pp16_feature_sharded_state",
    "validate_gate_c_hlo": "gate_c",
    "validate_integrated_checkpoint_success": "integrated_dense_rms",
    "validate_integrated_dense_rms_hlo": "integrated_dense_rms_hlo",
    "validate_integrated_dense_rms_stablehlo": "integrated_dense_rms_hlo",
    "validate_m2048_strategy_nd_fingerprint_hlo": "m2048_association_fingerprint",
    "validate_output_geometry_hlo": "output_geometry",
    "validate_output_geometry_stablehlo": "output_geometry",
    "validate_paired_transport_hlo": "paired_transport",
    "validate_pallas_real_layer_hlo": "one_layer",
    "validate_real_layer_hlo": "one_layer",
    "validate_sparse_attention_hlo": "sparse_attention",
    "validate_sparse_attention_integration_hlo": "sparse_attention",
    "validate_strategy_nd_dense_rms_hlo": "dense_rms_replay",
    "validate_strategy_nd_fingerprint_hlo": "association_fingerprint",
    "validate_transport_pairs": "transport_chain",
    "validate_ws32_decoder_hlo": "ws32_decoder",
    "validate_ws32_exact_dsa_materializer_hlo": "ws32_decoder",
    "validate_ws32_one_layer_hlo": "ws32_one_layer",
    "validate_ws32_pallas_one_layer_hlo": "ws32_pallas_one_layer",
    "validate_ws32_topology_fleet": "ws32_one_layer",
    "ws32_one_layer_inputs": "ws32_one_layer",
}

__all__ = [
    "ACCEPTED_SOURCE_VALIDITY",
    "ACCEPTED_DENSE_PARTIALS_KEYS",
    "ACCEPTED_DENSE_PARTIALS_NPZ_SHA256",
    "ACCEPTED_DENSE_PARTIALS_RAW_SHA256",
    "ACCEPTED_DENSE_PARTIALS_SHAPE",
    "ACCEPTED_DECODE_PROJECTION_HLO_GZIP_SHA256",
    "ACCEPTED_DECODE_PROJECTION_HLO_RAW_SHA256",
    "ACCEPTED_DECODE_PROJECTION_MANIFEST_SHA256",
    "ACCEPTED_TP32_MODEL_AXIS_RECIPE",
    "CollectiveChainConfig",
    "CollectiveKind",
    "CHECKPOINT_SUCCESS_SHA256",
    "DENSE_RMS_ARRAY_RECORDS",
    "DENSE_RMS_SOURCE_CODE_HASH",
    "DENSE_RMS_SOURCE_KEYS",
    "DENSE_RMS_SOURCE_NPZ_SHA256",
    "DENSE_RMS_SOURCE_REMOTE_OBJECTS_SHA256",
    "DENSE_RMS_SOURCE_RUNNER_SHA256",
    "DENSE_RMS_SOURCE_SUCCESS_SHA256",
    "DENSE_RMS_SOURCE_SUMMARY_SHA256",
    "DENSE_RMS_SOURCE_TAG",
    "DenseRmsInputs",
    "CompiledIntegratedDenseRms",
    "GateCDenseResult",
    "GateCDsaResult",
    "GateCIndexShareResult",
    "INTEGRATED_DENSE_RMS_STABLEHLO_SHA256",
    "INTEGRATED_DENSE_ACCEPTED_SOURCE_STABLEHLO_SHA256",
    "INTEGRATED_DENSE_NATIVE_SOURCE_OPTIMIZED_HLO_SHA256",
    "INTEGRATED_DENSE_NATIVE_SOURCE_STABLEHLO_SHA256",
    "INTEGRATED_DENSE_ORDINAL_RMS_STABLEHLO_SHA256",
    "INTEGRATED_DENSE_PREDENSE_SPLIT_RMS_STABLEHLO_SHA256",
    "INTEGRATED_DENSE_SPLIT_RMS_STABLEHLO_SHA256",
    "IntegratedDenseRmsInputs",
    "IntegratedDenseWeights",
    "NATIVE_SOURCE_ATTENDED_LATENT_SHA256",
    "NATIVE_SOURCE_ATTENDED_LATENT_KEY",
    "NATIVE_SOURCE_NPZ_SHA256",
    "NATIVE_SOURCE_REMOTE_OBJECTS_SHA256",
    "NATIVE_SOURCE_RUNNER_SHA256",
    "NATIVE_SOURCE_SUCCESS_SHA256",
    "NATIVE_SOURCE_SUMMARY_SHA256",
    "NATIVE_SOURCE_TAG",
    "NATIVE_SOURCE_TOKEN_IDS",
    "NativeSourceInputs",
    "NativeSourceWeights",
    "OutputGeometryInputs",
    "CompiledOutputGeometryReplay",
    "OUTPUT_GEOMETRY_OPTIMIZED_HLO_SHA256",
    "OUTPUT_GEOMETRY_DENSE_ROW_RAW_SHA256",
    "OUTPUT_GEOMETRY_INVERSE_RAW_SHA256",
    "OUTPUT_GEOMETRY_STABLEHLO_SHA256",
    "M1_AUTO_BF16_LAYOUT",
    "M1_PALLAS_M8_SCRATCH_SHAPE",
    "M32_BF16_LAYOUT",
    "POST_ATTENTION_NORM_RAW_SHA256",
    "assemble_native_source_weights",
    "LatencyDistribution",
    "PairedTransportConfig",
    "PairedTransportKind",
    "REAL_LAYER_OUTPUT_TOLERANCE",
    "ROUTE_WEIGHT_TOLERANCE",
    "STRATEGY_ND_ALGORITHM",
    "StrategyNdFingerprintConfig",
    "TensorTolerance",
    "accepted_tp32_model_axis_device_ids",
    "addressable_checksum",
    "analyze_m32_strategy_nd_fingerprint",
    "analyze_strategy_nd_fingerprint",
    "array_sha256",
    "benchmark_collective_chain",
    "benchmark_paired_transport",
    "build_collective_chain",
    "build_strategy_nd_fingerprint",
    "build_strategy_nd_dense_rms_replay",
    "build_integrated_dense_rms",
    "build_output_geometry_replay",
    "build_paired_transport",
    "pack_paired_transport_payload",
    "collective_chain_hlo_policy",
    "compare_bounded_tensor",
    "compare_output_geometry_arrays",
    "execute_strategy_nd_fingerprint",
    "execute_strategy_nd_dense_rms_replay",
    "execute_integrated_dense_rms",
    "execute_native_source_context",
    "execute_output_geometry_replay",
    "generate_strategy_nd_input_bits",
    "integrated_dense_rms_hlo_policy",
    "jax_dtype",
    "latency_distribution",
    "model_axis_to_physical_input_bits",
    "model_axis_weights_to_physical",
    "native_source_inputs",
    "load_dense_rms_inputs",
    "load_integrated_dense_rms_inputs",
    "load_output_geometry_inputs",
    "replay_db533_strategy_nd_row0_bits",
    "stage_local_dense_gate_c",
    "stage_local_dsa_fp8_gate_c",
    "stage_local_dsa_gate_c",
    "stage_local_index_share_gate_c",
    "validate_gate_c_hlo",
    "validate_dsa_score_hlo",
    "validate_sparse_attention_hlo",
    "validate_sparse_attention_integration_hlo",
    "validate_strategy_nd_fingerprint_hlo",
    "validate_strategy_nd_dense_rms_hlo",
    "validate_integrated_dense_rms_hlo",
    "validate_integrated_dense_rms_stablehlo",
    "validate_output_geometry_hlo",
    "validate_output_geometry_stablehlo",
    "validate_integrated_checkpoint_success",
    "TransportChainConfig",
    "TransportKind",
    "PP16_FEATURE2_ACCEPTED_CARRIED_HALF_SHA256",
    "PP16_FEATURE2_ACCEPTED_CARRIED_SHA256",
    "PP16_FEATURE2_ACCEPTED_DENSE_HALF_SHA256",
    "PP16_FEATURE2_ACCEPTED_DENSE_SHA256",
    "PP16_FEATURE2_ACCEPTED_INPUT_RESIDUAL_HALF_SHA256",
    "PP16_FEATURE2_ACCEPTED_INPUT_RESIDUAL_SHA256",
    "PP16_FEATURE2_CONTEXT_LENGTH",
    "PP16_FEATURE2_MINIMUM_STATE_BYTES_PER_DEVICE",
    "PP16_FEATURE2_N82_SCALE_SHA256",
    "PP16_FEATURE2_N82_WEIGHT_SHA256",
    "PP16_FEATURE2_RUNTIME_MANIFEST_SHA256",
    "PP16_FEATURE2_SELECTED_WEIGHT_BYTES_PER_DEVICE",
    "CompiledFeature2Boundary",
    "Feature2SplitRecord",
    "Feature2TensorRead",
    "LoweredFeature2Transport",
    "LoadedFeature2SelectiveCheckpoint",
    "Feature2PrefillGraph",
    "Feature2PrefillChunk",
    "Feature2PrefillInputs",
    "Feature2PrefillNode",
    "Feature2PrefillSource",
    "Feature2PrefillTensor",
    "Feature2WeightRole",
    "PP16_FEATURE2_CURRENT_POSITION",
    "PP16_FEATURE2_CURRENT_TOKEN_ID",
    "PP16_FEATURE2_DSA_TOP_K",
    "PP16_FEATURE2_LOCAL_GROUP",
    "PP16_FEATURE2_LOGICAL_PAGES",
    "PP16_FEATURE2_LOGICAL_PAGE_SIZE",
    "PP16_FEATURE2_LOCAL_ROWS_PER_PAGE",
    "PP16_FEATURE2_PREFILL_CHUNK",
    "PP16_FEATURE2_PREFILL_VALID_ROWS",
    "PP16_FEATURE2_SELECTED_READS_SHA256",
    "PP16_FEATURE2_TIE_POLICY",
    "WS32_ONE_LAYER_INPUT_SPECS",
    "WS32_ONE_LAYER_OUTPUT_SPEC",
    "WS32_PALLAS_REAL_LAYER_LIVE_CLOSURE_SHA256",
    "WS32_PALLAS_REAL_LAYER_OPTIMIZED_HLO_SHA256",
    "WS32_PALLAS_REAL_LAYER_STABLEHLO_SHA256",
    "Ws32PallasOneLayerHloReport",
    "Ws32DecoderHloReport",
    "Ws32ExactDsaMaterializerHloReport",
    "Ws32OneLayerHloReport",
    "benchmark_transport_chain",
    "build_transport_chain",
    "build_feature2_boundary",
    "build_feature2_prefill_graph",
    "derive_feature2_tensor_allowlist",
    "feature2_minimum_acquisition_roles",
    "lower_feature2_transport",
    "pp16_feature2_transport_pairs",
    "read_feature2_owner_headers",
    "inspect_feature2_selective_plan",
    "load_feature2_selective_checkpoint",
    "load_feature2_prefill_inputs",
    "split_feature2_bf16_bits",
    "build_ws32_one_layer_mapped",
    "build_ws32_pallas_one_layer_mapped",
    "transport_chain_hlo_policy",
    "validate_compiled_transport",
    "validate_pallas_real_layer_hlo",
    "validate_paired_transport_hlo",
    "unpack_paired_transport_payload",
    "validate_real_layer_hlo",
    "validate_transport_pairs",
    "validate_feature2_accepted_state",
    "validate_feature2_acquisition_reads",
    "validate_feature2_acquisition_scope",
    "validate_feature2_boundary_stablehlo",
    "validate_feature2_n82_manifest",
    "validate_feature2_prefill_graph",
    "validate_feature2_prefill_inputs",
    "validate_feature2_transport_contract",
    "validate_feature2_transport_stablehlo",
    "validate_ws32_one_layer_hlo",
    "validate_ws32_pallas_one_layer_hlo",
    "validate_ws32_decoder_hlo",
    "validate_ws32_exact_dsa_materializer_hlo",
    "validate_ws32_topology_fleet",
    "ws32_one_layer_inputs",
]


def __getattr__(name):
    module = _EXPORTS.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(_import_module("." + module, __name__), name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(_EXPORTS))
