"""Compact Pallas kernels for the greenfield TPU execution path."""

from .dsa import DsaScoreConfig, dsa_scores_kernel, dsa_scores_pallas
from .fp8_matmul import (
    Fp8BlockMatmulConfig,
    fp8_block_matmul,
    fp8_block_matmul_f32,
    fp8_block_vector_matmul_f32,
    fp8_block_up_gate,
    fp8_fused_block_swiglu,
    fp8_fused_selected_moe,
    fp8_fused_structured_kv_b_value_output,
    fp32_to_bf16_pallas_boundary,
    fp8_rmsnorm_block_matmul,
    fp8_structured_kv_b_q_absorb,
    fp8_structured_kv_b_value,
    fp8_selected_swiglu_down,
    fp8_selected_up_gate,
    fp8_strategy_nd_attention_matmul,
)
from .rmsnorm import (
    fused_add_rms_norm_m1,
    source_fused_output_m1_feature_tiled_m8,
    source_fused_output_m1_m8_scratch,
    weighted_output_m1_m8_scratch,
)
from .sparse_attention import (
    SparseMlaConfig,
    pregathered_sparse_mla_pallas,
    stage_local_sparse_mla_kernel,
    stage_local_sparse_mla_pallas,
)
from .stage_remote_copy import (
    StageRemoteCopyConfig,
    stage_remote_copy_kernel,
    stage_remote_copy_pallas,
    stage_value_remote_copy_kernel_name,
    stage_value_remote_copy_pallas,
)
from .topk import (
    DsaTopKConfig,
    local_topk_candidates_kernel,
    local_topk_candidates_pallas,
    merge_topk_candidates_kernel,
    merge_topk_candidates_pallas,
)

__all__ = [
    "DsaScoreConfig",
    "DsaTopKConfig",
    "Fp8BlockMatmulConfig",
    "SparseMlaConfig",
    "StageRemoteCopyConfig",
    "dsa_scores_kernel",
    "dsa_scores_pallas",
    "fp8_block_matmul",
    "fused_add_rms_norm_m1",
    "source_fused_output_m1_feature_tiled_m8",
    "source_fused_output_m1_m8_scratch",
    "weighted_output_m1_m8_scratch",
    "fp8_block_matmul_f32",
    "fp8_block_vector_matmul_f32",
    "fp8_block_up_gate",
    "fp8_fused_block_swiglu",
    "fp8_fused_selected_moe",
    "fp8_fused_structured_kv_b_value_output",
    "fp32_to_bf16_pallas_boundary",
    "fp8_rmsnorm_block_matmul",
    "fp8_structured_kv_b_q_absorb",
    "fp8_structured_kv_b_value",
    "fp8_selected_swiglu_down",
    "fp8_selected_up_gate",
    "fp8_strategy_nd_attention_matmul",
    "local_topk_candidates_kernel",
    "local_topk_candidates_pallas",
    "merge_topk_candidates_kernel",
    "merge_topk_candidates_pallas",
    "pregathered_sparse_mla_pallas",
    "stage_local_sparse_mla_kernel",
    "stage_local_sparse_mla_pallas",
    "stage_remote_copy_kernel",
    "stage_remote_copy_pallas",
    "stage_value_remote_copy_kernel_name",
    "stage_value_remote_copy_pallas",
]
