"""On-demand validation exports for the native engine and retained inspectors.

Importing one validator must not eagerly import every legacy capture workflow.
Named targets are unchanged; research-only exports still need individual
adjudication. The old __all__ also advertised an unbound Ws32LongContextOracle;
that broken package alias is omitted (the class remains in its own module).
No validator bodies, numerical source or admission identities change here.
"""

from importlib import import_module as _import_module

_EXPORTS = {
    "AcceptedAttentionOutputCaptureConfig": "attention_output_operand",
    "AcceptedAttentionProjectionCaptureConfig": "attention_output_operand",
    "AcceptedAttentionUpdateCaptureConfig": "attention_update",
    "AcceptedDenseBoundaryCaptureConfig": "dense_boundary",
    "AcceptedDenseInputCaptureConfig": "dense_input",
    "AcceptedGreenfieldDsaInternalComparisonConfig": "legacy_dsa_internals",
    "ArrayObservation": "observability",
    "AttentionOutputComparisonConfig": "attention_output_operand",
    "AttentionProjectionComparisonConfig": "attention_output_operand",
    "AttentionUpdateComparisonConfig": "attention_update",
    "DenseBoundaryComparisonConfig": "dense_boundary",
    "DenseInputComparisonConfig": "dense_input",
    "GateCOracleConfig": "gate_c_oracle",
    "LegacyDsaInternalCaptureConfig": "legacy_dsa_internals",
    "LegacyDsaInternalComparisonConfig": "legacy_dsa_internals",
    "LegacyMainCacheComparisonConfig": "legacy_main_cache",
    "LegacyPromptIndexCacheConfig": "prompt_index_cache",
    "LegacyPromptKeyInternalConfig": "prompt_index_cache",
    "LegacyResidualComparisonConfig": "legacy_residuals",
    "LongContextOracleConfig": "long_context_oracle",
    "OneLayerOracleConfig": "one_layer_oracle",
    "ShortContextDsaOracleConfig": "short_context_dsa_oracle",
    "ShortContextLogprobOracleConfig": "short_context_logprob_oracle",
    "ShortContextOracleConfig": "short_context_oracle",
    "Ws32AdjudicatedDivergence": "ws32_short_context",
    "Ws32ShortContextOracle": "ws32_short_context",
    "audit_observability_contract": "observability",
    "bind_ws32_adjudication": "ws32_short_context",
    "capture_accepted_attention_output_operand": "attention_output_operand",
    "capture_accepted_attention_projection_operands": "attention_output_operand",
    "capture_accepted_attention_update": "attention_update",
    "capture_accepted_dense_boundary": "dense_boundary",
    "capture_accepted_dense_input": "dense_input",
    "capture_gate_c_oracle": "gate_c_oracle",
    "capture_legacy_prompt_index_cache": "prompt_index_cache",
    "capture_long_context_oracle": "long_context_oracle",
    "capture_one_layer_oracle": "one_layer_oracle",
    "capture_short_context_dsa_oracle": "short_context_dsa_oracle",
    "capture_short_context_logprob_oracle": "short_context_logprob_oracle",
    "capture_short_context_oracle": "short_context_oracle",
    "compare_accepted_greenfield_dsa_internal_observation": "legacy_dsa_internals",
    "compare_array_observations": "observability",
    "compare_attention_output_operands": "attention_output_operand",
    "compare_attention_projection_operands": "attention_output_operand",
    "compare_attention_update_candidates": "attention_update",
    "compare_dense_boundary_candidate": "dense_boundary",
    "compare_dense_input_candidate": "dense_input",
    "compare_dsa_association_scores": "layer0_dsa_association",
    "compare_legacy_dsa_internals": "legacy_dsa_internals",
    "compare_legacy_layer0_main_cache": "legacy_main_cache",
    "compare_legacy_residuals": "legacy_residuals",
    "compare_prompt_index_key_bits": "prompt_index_cache",
    "compare_prompt_key_internal_states": "prompt_index_cache",
    "compare_prompt_projection_input": "prompt_index_cache",
    "compare_short_context_dsa_oracles": "short_context_dsa_oracle",
    "compare_ws32_dsa_step": "ws32_short_context",
    "compare_ws32_dsa_within_engine": "ws32_short_context",
    "compare_ws32_raw_tokens": "ws32_short_context",
    "inspect_distributed_q_a_norm_artifact": "layer0_dsa_association",
    "inspect_gate_c_oracle": "gate_c_oracle",
    "inspect_greenfield_layer0_dsa_internal_observation": "layer0_dsa_association",
    "inspect_greenfield_layer0_dsa_selected_observation": "layer0_dsa_association",
    "inspect_layer0_dsa_association_input": "layer0_dsa_association",
    "inspect_legacy_dsa_internal_capture": "legacy_dsa_internals",
    "inspect_legacy_prompt_index_cache": "prompt_index_cache",
    "inspect_legacy_prompt_key_internal_capture": "prompt_index_cache",
    "inspect_long_context_oracle": "long_context_oracle",
    "inspect_npz_artifact": "observability",
    "inspect_one_layer_oracle": "one_layer_oracle",
    "inspect_prompt_key_internal_capture_artifact": "prompt_index_cache",
    "inspect_short_context_dsa_oracle": "short_context_dsa_oracle",
    "inspect_short_context_logprob_oracle": "short_context_logprob_oracle",
    "inspect_short_context_oracle": "short_context_oracle",
    "load_legacy_bench_module": "long_context_oracle",
    "load_ws32_adjudicated_divergence": "ws32_short_context",
    "load_ws32_long_context_oracle": "long_context_oracle",
    "load_ws32_short_context_oracle": "ws32_short_context",
    "normalize_sample_logprobs": "short_context_logprob_oracle",
    "pack_stage_local_index_keys": "layer0_dsa_association",
    "stitch_stage_local_scores": "layer0_dsa_association",
    "validate_output_geometry_replay": "output_geometry",
    "validate_prompt_index_key_association_hlo": "prompt_index_cache",
    "validate_prompt_index_key_probe_hlo": "prompt_index_cache",
    "validate_prompt_projection_input_hlo": "prompt_index_cache",
    "validate_strategy_nd_dense_replay": "strategy_nd_dense_replay",
    "validate_strategy_nd_dense_rms_replay": "strategy_nd_dense_rms_replay",
    "validate_strategy_nd_integrated_dense_rms": "strategy_nd_integrated_dense_rms",
    "validate_ws32_cache_probe": "ws32_short_context",
    "write_observability_report": "observability",
}

__all__ = (
    "AcceptedAttentionUpdateCaptureConfig",
    "AcceptedAttentionOutputCaptureConfig",
    "AcceptedAttentionProjectionCaptureConfig",
    "AttentionOutputComparisonConfig",
    "AttentionProjectionComparisonConfig",
    "AttentionUpdateComparisonConfig",
    "AcceptedDenseBoundaryCaptureConfig",
    "AcceptedDenseInputCaptureConfig",
    "DenseBoundaryComparisonConfig",
    "DenseInputComparisonConfig",
    "GateCOracleConfig",
    "OneLayerOracleConfig",
    "AcceptedGreenfieldDsaInternalComparisonConfig",
    "ArrayObservation",
    "LegacyResidualComparisonConfig",
    "LegacyMainCacheComparisonConfig",
    "LegacyDsaInternalCaptureConfig",
    "LegacyDsaInternalComparisonConfig",
    "LegacyPromptKeyInternalConfig",
    "LegacyPromptIndexCacheConfig",
    "LongContextOracleConfig",
    "ShortContextOracleConfig",
    "capture_long_context_oracle",
    "inspect_long_context_oracle",
    "ShortContextDsaOracleConfig",
    "ShortContextLogprobOracleConfig",
    "Ws32AdjudicatedDivergence",
    "bind_ws32_adjudication",
    "Ws32ShortContextOracle",
    "capture_gate_c_oracle",
    "capture_accepted_attention_output_operand",
    "capture_accepted_attention_projection_operands",
    "capture_accepted_attention_update",
    "capture_accepted_dense_boundary",
    "capture_accepted_dense_input",
    "capture_one_layer_oracle",
    "capture_legacy_prompt_index_cache",
    "compare_prompt_key_internal_states",
    "compare_prompt_index_key_bits",
    "compare_prompt_projection_input",
    "compare_attention_output_operands",
    "compare_attention_projection_operands",
    "compare_attention_update_candidates",
    "compare_dense_boundary_candidate",
    "compare_dense_input_candidate",
    "compare_accepted_greenfield_dsa_internal_observation",
    "compare_legacy_residuals",
    "compare_legacy_layer0_main_cache",
    "compare_legacy_dsa_internals",
    "inspect_legacy_dsa_internal_capture",
    "inspect_legacy_prompt_key_internal_capture",
    "inspect_prompt_key_internal_capture_artifact",
    "capture_short_context_oracle",
    "capture_short_context_dsa_oracle",
    "compare_short_context_dsa_oracles",
    "capture_short_context_logprob_oracle",
    "audit_observability_contract",
    "compare_array_observations",
    "compare_dsa_association_scores",
    "compare_ws32_dsa_step",
    "compare_ws32_dsa_within_engine",
    "load_legacy_bench_module",
    "load_ws32_long_context_oracle",
    "compare_ws32_raw_tokens",
    "inspect_gate_c_oracle",
    "inspect_distributed_q_a_norm_artifact",
    "inspect_greenfield_layer0_dsa_internal_observation",
    "inspect_greenfield_layer0_dsa_selected_observation",
    "inspect_layer0_dsa_association_input",
    "inspect_one_layer_oracle",
    "inspect_npz_artifact",
    "inspect_legacy_prompt_index_cache",
    "validate_prompt_index_key_association_hlo",
    "validate_prompt_index_key_probe_hlo",
    "validate_prompt_projection_input_hlo",
    "inspect_short_context_oracle",
    "inspect_short_context_dsa_oracle",
    "inspect_short_context_logprob_oracle",
    "load_ws32_adjudicated_divergence",
    "load_ws32_short_context_oracle",
    "normalize_sample_logprobs",
    "pack_stage_local_index_keys",
    "stitch_stage_local_scores",
    "validate_strategy_nd_dense_replay",
    "validate_strategy_nd_dense_rms_replay",
    "validate_strategy_nd_integrated_dense_rms",
    "validate_output_geometry_replay",
    "validate_ws32_cache_probe",
    "write_observability_report",
)


def __getattr__(name):
    module = _EXPORTS.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(_import_module("." + module, __name__), name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(_EXPORTS))
