"""Readable exactness-first JAX reference kernels."""

from .attention import (
    CanonicalSelectedPositions,
    MlaNumericalContract,
    SelectedKvSegment,
    SparseAttentionResult,
    StageLocalKvLayout,
    canonicalize_selected_positions,
    combine_stage_local_attention,
    gather_paged_selected_kv,
    gather_stage_local_selected_kv,
    selected_positions_for_owner,
    sparse_mla_attention,
    stage_local_sparse_mla_reference,
)
from .fp8 import dequantize_fp8_bits_block_weight, fp8_e4m3fn_lookup
from .dsa import (
    DsaNumericalContract,
    SelectedPositions,
    distributed_exact_topk_reference,
    dsa_index_keys,
    dsa_query_and_head_weights,
    dsa_scores,
    exact_topk,
    local_topk_candidates,
    merge_topk_candidates,
)
from .linear import (
    dense_swiglu,
    embedding_lookup,
    linear,
    residual_add,
    silu,
    vocabulary_logits,
)
from .index_share import (
    IndexShareSchedule,
    IndexShareState,
    pack_index_share_transfer,
    produce_index_share_state,
    resolve_index_share_layer,
    restore_index_share_transfer,
    validate_index_share_state_host,
)
from .moe import (
    GlmMoeNumericalContract,
    dequantize_fp8_block_weight,
    reference_moe_from_routes,
    route_glm_noaux_tc,
    route_glm_noaux_tc_logits,
    stage_local_moe,
    stage_local_moe_from_routes,
)
from .rmsnorm import final_norm, rms_norm
from .rotary import apply_rotary, rotary_cos_sin

__all__ = (
    "CanonicalSelectedPositions",
    "DsaNumericalContract",
    "GlmMoeNumericalContract",
    "IndexShareSchedule",
    "IndexShareState",
    "MlaNumericalContract",
    "SelectedKvSegment",
    "SelectedPositions",
    "SparseAttentionResult",
    "StageLocalKvLayout",
    "apply_rotary",
    "canonicalize_selected_positions",
    "combine_stage_local_attention",
    "dequantize_fp8_bits_block_weight",
    "fp8_e4m3fn_lookup",
    "dequantize_fp8_block_weight",
    "dense_swiglu",
    "distributed_exact_topk_reference",
    "dsa_index_keys",
    "dsa_query_and_head_weights",
    "dsa_scores",
    "embedding_lookup",
    "exact_topk",
    "final_norm",
    "gather_paged_selected_kv",
    "gather_stage_local_selected_kv",
    "linear",
    "local_topk_candidates",
    "merge_topk_candidates",
    "pack_index_share_transfer",
    "produce_index_share_state",
    "reference_moe_from_routes",
    "residual_add",
    "resolve_index_share_layer",
    "restore_index_share_transfer",
    "rms_norm",
    "rotary_cos_sin",
    "route_glm_noaux_tc",
    "route_glm_noaux_tc_logits",
    "selected_positions_for_owner",
    "silu",
    "stage_local_moe",
    "stage_local_moe_from_routes",
    "sparse_mla_attention",
    "stage_local_sparse_mla_reference",
    "validate_index_share_state_host",
    "vocabulary_logits",
)
